### ISSUE TITLE
Cookie with encryption key expires earlier than Django session

### ISSUE THREAD

**Issue by sergray** [solex/django-odesk#12]
I'm using Django 1.4.2 with default settings and django-odesk c545e320d3cab5.

_oekey_ cookie expires earlier than _sessionid_, so user is authenticated, but calls to oDesk API using methods of _RequestClient_'s instance end up with server errors.

**Comment by sergray** [comment]
Created Django 1.4.3 project reproducing the problem https://github.com/sergray/django-odesk-issue-12

**Comment by solex** [comment]
Kostia wrote that part, so I assigned the issue to him. Let's hope his reaction time is better than mine :)
